[2024-05-10T14:41:49.924+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T14:41:49.949+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.concat_data manual__2024-05-10T10:18:14.377791+00:00 [queued]>
[2024-05-10T14:41:49.958+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.concat_data manual__2024-05-10T10:18:14.377791+00:00 [queued]>
[2024-05-10T14:41:49.960+0000] {taskinstance.py:2306} INFO - Starting attempt 40 of 43
[2024-05-10T14:41:49.972+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): concat_data> on 2024-05-10 10:18:14.377791+00:00
[2024-05-10T14:41:49.979+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=12472) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-10T14:41:49.980+0000] {standard_task_runner.py:63} INFO - Started process 12474 to run task
[2024-05-10T14:41:49.979+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'concat_data', 'manual__2024-05-10T10:18:14.377791+00:00', '--job-id', '610', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpnr91avs4']
[2024-05-10T14:41:49.981+0000] {standard_task_runner.py:91} INFO - Job 610: Subtask concat_data
[2024-05-10T14:41:49.995+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-10T14:41:50.026+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline.concat_data manual__2024-05-10T10:18:14.377791+00:00 [running]> on host dbfcb70dcca2
[2024-05-10T14:41:50.223+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='concat_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T10:18:14.377791+00:00' AIRFLOW_CTX_TRY_NUMBER='40' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-10T10:18:14.377791+00:00'
[2024-05-10T14:41:50.224+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T14:41:50.277+0000] {logging_mixin.py:188} INFO - 0      2017
1      2017
2      2017
3      2016
4      2016
       ... 
995    2017
996    2017
997    2017
998    2017
999    2017
Name: publication_year, Length: 1000, dtype: object
[2024-05-10T14:41:51.438+0000] {logging_mixin.py:188} INFO - Uploaded data/database.csv to Minio
[2024-05-10T14:41:51.439+0000] {logging_mixin.py:188} INFO - 0        ['Stanford University School of Medicine', 'Ch...
1                             ['Chulalongkorn University']
2                             ['Chulalongkorn University']
3        ['Hirosaki University', 'Chulalongkorn Univers...
4        ['Chulalongkorn University', 'Thailand Nationa...
                               ...                        
22114     [Chulalongkorn University, Yamaguchi University]
22116                           [Chulalongkorn University]
22117    [Tokyo Institute of Technology, Chulalongkorn ...
22118      [Chulalongkorn University, Hokkaido University]
22120    [Chulalongkorn University, King Mongkut's Univ...
Name: affiliation_name, Length: 21752, dtype: object
[2024-05-10T14:41:51.440+0000] {python.py:237} INFO - Done. Returned value was:                                                    title  ...                                           keywords
0      Public health and international epidemiology f...  ...                                                 []
1      Flexible Printed Active Antenna for Digital Te...  ...                                                 []
2      Parametric study of hydrogen production via so...  ...  ['Circulating fluidized bed', 'Computational f...
3      Superhydrophobic coating from fluoroalkylsilan...  ...  ['Encapsulation', 'Fluoroalkylsilane', 'Natura...
4      Electrochemical impedance based DNA sensor usi...  ...  ['acpcPNA', 'Electrochemical impedance spectro...
...                                                  ...  ...                                                ...
22114  Study of the liquid-film-forming apparatus as ...  ...  [Alternative aeration system, aquaculture pond...
22116  Towards 5G cellular: Understanding 3D in-build...  ...  [5G, Architecture, Control-/user-plane, Femtoc...
22117  Modeling of root-reinforced soil slope under r...  ...  [Centrifuge modeling, Landslides, Seepage anal...
22118  Production of massoia lactone by Aureobasidium...  ...  [Aureobasidium pullulans, fragrant biosurfacta...
22120  Two-dimensional modeling of the oxidative coup...  ...  [Fixed bed reactor, Gas hour space velocity (G...

[21752 rows x 5 columns]
[2024-05-10T14:41:51.453+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T14:41:51.479+0000] {xcom.py:675} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-05-10T14:41:51.481+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 148, in serialize
    data, serialized_classname, version, is_serialized = _serializers[qn].serialize(o)
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serializers/pandas.py", line 49, in serialize
    table = pa.Table.from_pandas(o)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/table.pxi", line 4525, in pyarrow.lib.Table.from_pandas
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/pandas_compat.py", line 624, in dataframe_to_arrays
    arrays[i] = maybe_fut.result()
                ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/pandas_compat.py", line 598, in convert_column
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/pandas_compat.py", line 592, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/array.pxi", line 345, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 85, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ("Expected bytes, got a 'numpy.ndarray' object", 'Conversion failed for column affiliation_name with type object')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 486, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3197, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 246, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 673, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2024-05-10T14:41:51.491+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline, task_id=concat_data, run_id=manual__2024-05-10T10:18:14.377791+00:00, execution_date=20240510T101814, start_date=20240510T144149, end_date=20240510T144151
[2024-05-10T14:41:51.502+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 610 for task concat_data (Object of type DataFrame is not JSON serializable; 12474)
[2024-05-10T14:41:51.519+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-10T14:41:51.537+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-10T14:41:51.539+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
