[2024-05-10T14:53:14.372+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T14:53:14.398+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.concat_data manual__2024-05-10T10:18:14.377791+00:00 [queued]>
[2024-05-10T14:53:14.406+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.concat_data manual__2024-05-10T10:18:14.377791+00:00 [queued]>
[2024-05-10T14:53:14.407+0000] {taskinstance.py:2306} INFO - Starting attempt 44 of 47
[2024-05-10T14:53:14.417+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): concat_data> on 2024-05-10 10:18:14.377791+00:00
[2024-05-10T14:53:14.425+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=13009) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-10T14:53:14.426+0000] {standard_task_runner.py:63} INFO - Started process 13011 to run task
[2024-05-10T14:53:14.425+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'concat_data', 'manual__2024-05-10T10:18:14.377791+00:00', '--job-id', '622', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmptlkdwbbd']
[2024-05-10T14:53:14.428+0000] {standard_task_runner.py:91} INFO - Job 622: Subtask concat_data
[2024-05-10T14:53:14.440+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-10T14:53:14.469+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline.concat_data manual__2024-05-10T10:18:14.377791+00:00 [running]> on host dbfcb70dcca2
[2024-05-10T14:53:14.668+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='concat_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T10:18:14.377791+00:00' AIRFLOW_CTX_TRY_NUMBER='44' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-10T10:18:14.377791+00:00'
[2024-05-10T14:53:14.669+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T14:53:14.686+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T14:53:14.686+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/concat_data.py", line 23, in concat_data
    print(df['publication_year'])
          ~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-05-10T14:53:14.696+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline, task_id=concat_data, run_id=manual__2024-05-10T10:18:14.377791+00:00, execution_date=20240510T101814, start_date=20240510T145314, end_date=20240510T145314
[2024-05-10T14:53:14.707+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 622 for task concat_data ('NoneType' object is not subscriptable; 13011)
[2024-05-10T14:53:14.720+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-10T14:53:14.742+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-10T14:53:14.744+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
