[2024-05-10T07:13:54.316+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T07:13:54.339+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.clean_api_data manual__2024-05-10T06:58:08.348241+00:00 [queued]>
[2024-05-10T07:13:54.347+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.clean_api_data manual__2024-05-10T06:58:08.348241+00:00 [queued]>
[2024-05-10T07:13:54.347+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2024-05-10T07:13:54.358+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): clean_api_data> on 2024-05-10 06:58:08.348241+00:00
[2024-05-10T07:13:54.367+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=19929) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-10T07:13:54.368+0000] {standard_task_runner.py:63} INFO - Started process 19931 to run task
[2024-05-10T07:13:54.366+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'clean_api_data', 'manual__2024-05-10T06:58:08.348241+00:00', '--job-id', '300', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp8z74on2e']
[2024-05-10T07:13:54.369+0000] {standard_task_runner.py:91} INFO - Job 300: Subtask clean_api_data
[2024-05-10T07:13:54.382+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-10T07:13:54.413+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline.clean_api_data manual__2024-05-10T06:58:08.348241+00:00 [running]> on host 3031e573f05c
[2024-05-10T07:13:54.490+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='clean_api_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T06:58:08.348241+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-10T06:58:08.348241+00:00'
[2024-05-10T07:13:54.491+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T07:13:54.558+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/tasks/clean_data.py:50 FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
[2024-05-10T07:13:54.561+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T07:13:54.562+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/clean_data.py", line 50, in clean_api_data
    df.applymap(lambda x: re.sub(r'[^\x00-\x7F]+','', x))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 10174, in applymap
    return self.map(func, na_action=na_action, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 10120, in map
    return self.apply(infer).__finalize__(self, "map")
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 10034, in apply
    return op.apply().__finalize__(self, method="apply")
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 837, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 965, in apply_standard
    results, res_index = self.apply_series_generator()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 981, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 10118, in infer
    return x._map_values(func, na_action=na_action)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/base.py", line 921, in _map_values
    return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/algorithms.py", line 1814, in map_array
    return lib.map_infer(values, mapper, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib.pyx", line 2926, in pandas._libs.lib.map_infer
  File "/opt/airflow/dags/tasks/clean_data.py", line 50, in <lambda>
    df.applymap(lambda x: re.sub(r'[^\x00-\x7F]+','', x))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/re/__init__.py", line 186, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'list'
[2024-05-10T07:13:54.576+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=data_pipeline, task_id=clean_api_data, run_id=manual__2024-05-10T06:58:08.348241+00:00, execution_date=20240510T065808, start_date=20240510T071354, end_date=20240510T071354
[2024-05-10T07:13:54.586+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 300 for task clean_api_data (expected string or bytes-like object, got 'list'; 19931)
[2024-05-10T07:13:54.622+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-10T07:13:54.646+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-10T07:13:54.650+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
